name: MLOps CI

on:
    push:
        branches: [ main ]
        paths:
            - Dockerfile
            - Dockerfile.api
            - requirements.txt
            - api/**

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            
            # ----------------------
            # Train image
            # ----------------------
            - name: Build churn-train image
              run: |
                  docker build \
                    -t ${{ secrets.DOCKER_USERNAME }}/churn-train:latest \
                    -f Dockerfile .
            
            - name: Push churn-train image
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/churn-train:latest
            
            # ----------------------
            # API image
            # ----------------------
            - name: Build churn-api image
              run: |
                  docker build \
                    -t ${{ secrets.DOCKER_USERNAME }}/churn-api:latest \
                    -f Dockerfile.api .
            
            - name: Push churn-api image
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/churn-api:latest
